// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Client struct {
	ID           string          `db:"id" json:"id"`
	Name         string          `db:"name" json:"name"`
	CreatedAt    time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time       `db:"updated_at" json:"updated_at"`
	HourlyRate   sql.NullFloat64 `db:"hourly_rate" json:"hourly_rate"`
	CompanyName  sql.NullString  `db:"company_name" json:"company_name"`
	ContactName  sql.NullString  `db:"contact_name" json:"contact_name"`
	Email        sql.NullString  `db:"email" json:"email"`
	Phone        sql.NullString  `db:"phone" json:"phone"`
	AddressLine1 sql.NullString  `db:"address_line1" json:"address_line1"`
	AddressLine2 sql.NullString  `db:"address_line2" json:"address_line2"`
	City         sql.NullString  `db:"city" json:"city"`
	State        sql.NullString  `db:"state" json:"state"`
	PostalCode   sql.NullString  `db:"postal_code" json:"postal_code"`
	Country      sql.NullString  `db:"country" json:"country"`
	TaxNumber    sql.NullString  `db:"tax_number" json:"tax_number"`
	Dir          sql.NullString  `db:"dir" json:"dir"`
}

type Session struct {
	ID          string          `db:"id" json:"id"`
	ClientID    string          `db:"client_id" json:"client_id"`
	StartTime   time.Time       `db:"start_time" json:"start_time"`
	EndTime     sql.NullTime    `db:"end_time" json:"end_time"`
	Description sql.NullString  `db:"description" json:"description"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
	HourlyRate  sql.NullFloat64 `db:"hourly_rate" json:"hourly_rate"`
}
