// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteAllSessions(ctx context.Context) error
	DeleteSessionsByDateRange(ctx context.Context, arg DeleteSessionsByDateRangeParams) error
	GetActiveSession(ctx context.Context) (GetActiveSessionRow, error)
	GetClientById(ctx context.Context, id string) (Client, error)
	GetClientByName(ctx context.Context, name string) (Client, error)
	GetSessionsByClient(ctx context.Context, clientName string) ([]GetSessionsByClientRow, error)
	GetSessionsByDateRange(ctx context.Context, arg GetSessionsByDateRangeParams) ([]GetSessionsByDateRangeRow, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListRecentSessions(ctx context.Context, limitCount int64) ([]ListRecentSessionsRow, error)
	ListSessionsWithDateRange(ctx context.Context, arg ListSessionsWithDateRangeParams) ([]ListSessionsWithDateRangeRow, error)
	StopSession(ctx context.Context, arg StopSessionParams) (Session, error)
	UpdateClientBilling(ctx context.Context, arg UpdateClientBillingParams) (Client, error)
	UpdateClientRate(ctx context.Context, arg UpdateClientRateParams) (Client, error)
}

var _ Querier = (*Queries)(nil)
